# Generated by Django 6.0.5 on 2026-05-26 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='current_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_beds', to='ai_App.patient'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(help_text='Clinical diagnosis notes')),
                ('medications', models.TextField(help_text='List of prescribed medicines, dosage, and frequency')),
                ('instructions', models.TextField(blank=True, help_text='Patient instructions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='ai_App.appointment')),
            ],
        ),
    ]
