# Generated by Django 6.0.5 on 2026-05-30 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_App', '0002_bed_current_patient_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelehealthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_token', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sdp_offer', models.TextField(blank=True, help_text='SDP Offer signal string', null=True)),
                ('sdp_answer', models.TextField(blank=True, help_text='SDP Answer signal string', null=True)),
                ('ice_candidates_doc', models.TextField(blank=True, help_text='Doctor ICE candidates JSON array string', null=True)),
                ('ice_candidates_pat', models.TextField(blank=True, help_text='Patient ICE candidates JSON array string', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telehealth_session', to='ai_App.appointment')),
            ],
        ),
    ]
