# Generated by Django 6.0.5 on 2026-05-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_App', '0003_telehealthsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_medium',
            field=models.CharField(choices=[('In-Hospital', 'In-Hospital Physical Visit'), ('Video-Call', 'Online Video Consultation')], default='In-Hospital', max_length=20),
        ),
    ]
