# Generated by Django 5.1.6 on 2026-05-31 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_App', '0005_telehealthsession_is_on_hold_alter_appointment_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('shift_status', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurses', to='ai_App.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientVitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.PositiveIntegerField(blank=True, help_text='bpm', null=True)),
                ('blood_pressure', models.CharField(blank=True, help_text='e.g. 120/80', max_length=15, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='°F', max_digits=5, null=True)),
                ('blood_oxygen', models.PositiveIntegerField(blank=True, help_text='%', null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals_logs', to='ai_App.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_App.nurse')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
