# Generated by Django 5.1.6 on 2026-05-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_App', '0006_nurse_patientvitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='aftercare_plan',
            field=models.TextField(blank=True, help_text='AI Generated Diet and Aftercare Plan', null=True),
        ),
    ]
