# Generated by Django 5.1.6 on 2026-05-31 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_App', '0007_prescription_aftercare_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIClinicalReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('report_type', models.CharField(help_text='e.g. Cardiac Risk Profiler', max_length=100)),
                ('report_data', models.TextField(help_text='JSON string of the AI output')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to='ai_App.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to='ai_App.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
