# Generated by Django 5.1.6 on 2026-06-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_App', '0008_aiclinicalreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True, help_text='Past medical history (e.g., surgeries, chronic conditions, allergies)', null=True),
        ),
    ]
